### ISSUE TITLE
Easy way to detect if a email exists in any list?

### ISSUE THREAD

**Issue by LucusWebsites** [laposta/laposta-api-php#3]
Is there a (quick) way to detect if a email exists in any list?
For now I use this litte snippet, but it feels wrong to fetch all subscribers just to check if someone is allready a subscriber:

```PHP
$memberExistsInList = false;
$member = new \Laposta_Member(\Settings\Laposta::LIST_ID);
$result = $member->all();
foreach ($result['data'] as $key => $member) {
    if ($member['member']['email'] === $email) {
        $memberExistsInList = true;
    }
}

**Comment by stijnvanderree** [comment]
Hm, there seems to be no better way. We'll add a function for that next week.

**Comment by stijnvanderree** [comment]
On closer inspection: you can just request the member from the list and see if it exists. A member can be identified by it's id, but also by email address.

You need to do this for each list, but there's no need for looping through the members.

```
$memberExistsInList = false;
$member = new \Laposta_Member(\Settings\Laposta::LIST_ID);
$result = $member->get($email);
// test result
```

Will this work for you?
